### ISSUE TITLE
Add boss timer

### ISSUE THREAD

**Issue by tzerk** [tzerk/BDO-Watchdog#7]
Resources
* [Urzas World Boss Timer](http://urzasarchives.com/bdo/wbtbdo/)
* [Simple web scraper](https://schier.co/blog/2015/04/26/a-simple-web-scraper-in-go.html)

Expected behavior:
* Parse the boss  timer page every X seconds and send a Telegram message if a spawn window opened

**Comment by Zumochi** [comment]
I personally don't see a need for this. I think the application does what it's supposed to do :)

Adding complexity for this seems unnecessary to me as there are plenty of other methods to check what's outlined here.

**Comment by tzerk** [comment]
You are probably right, there is no real need for it, especially when considering the existence of the Discord IHA channels. Thanks for you feedback!
